repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.13
  hooks:
    # ruff linter - on par with `uvx ruff check`
    - id: ruff-check
    # ruff formatter - on par with `uvx ruff format`
    - id: ruff-format

- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.9.26
  hooks:
    # run uv lock and upgrade - on par with `uv lock && uv lock --upgrade`
    - id: uv-lock
      args: [--upgrade]

